easy_admin:
    design:
        brand_color: '#1ABC9C'
        color_scheme: 'light'
    site_name: 'Blog backoffice'
    entities:

        User:
            class: App\Entity\User
            list:
                fields: ['id','name']
        Article:
            class: App\Entity\Article
            list:
                form_filters:
                    - user
                title: "all blog posts"


        Comment:
            class: App\Entity\Comment
            list:
                fields: ['id','body','article']
                title: "all comments"
        # List the entity class name you want to manage
         #- App\Entity\Apartment
        #- App\Entity\Article
        #- App\Entity\Comment
